# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-26 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('field', models.CharField(choices=[('Science', 'science'), ('Arts ', 'arts'), ('skills', 'skills')], default='all', max_length=100)),
                ('text', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='documents/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
