# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-27 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=300)),
                ('school', models.CharField(max_length=100)),
                ('teacher', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=300)),
            ],
        ),
    ]
