# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-28 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20170728_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bio',
            new_name='job',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='teacher',
        ),
    ]
