# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-31 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
