# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-07 09:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0013_friendmgmt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendmgmt',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friendmgmt',
            name='user',
        ),
        migrations.AddField(
            model_name='friendmgmt',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
