# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-07 10:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0014_auto_20170807_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendmgmt',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
